CREATE NONCLUSTERED INDEX [TB_PEDIDO_FILHOW01] ON [dbo].[TB_PEDIDO_FILHO] ([ID_PEDIDO_PAI]) WITH(FILLFACTOR = 90, DATA_COMPRESSION = PAGE, ONLINE = ON)
GO

CREATE NONCLUSTERED INDEX [TB_PEDIDO_PAI] ON [dbo].[TB_PEDIDO_PAI] ([ID_ENDERECO_CLIENTE_ENTREGA],[DT_HORA_FECHOU_PEDIDO]) WITH(FILLFACTOR = 90, DATA_COMPRESSION = PAGE, ONLINE=ON)
GO